version: '3.5'

services:
  my_db:
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=my_db
    image: postgres:10.6-alpine
  nats:
    container_name: nats_server
    ports:
      - "4222:4222"
    image: nats